import ants, importlib
importlib.reload(ants)
hive = ants.Hive(ants.AssaultPlan())
dimensions = (2, 9)
colony = ants.AntColony(None, hive, ants.ant_types(), ants.dry_layout, dimensions)

queen_tunnel, side_tunnel = [[colony.places['tunnel_{0}_{1}'.format(i, j)] for j in range(9)] for i in range(2)]
queen = ants.QueenAnt()
queen_tunnel[7].add_insect(queen)
print('Turn1----------------------------')
thrower = ants.ThrowerAnt()
fire = ants.FireAnt()
ninja = ants.NinjaAnt()
side = ants.ThrowerAnt()
front = ants.NinjaAnt()
queen_tunnel[0].add_insect(thrower)
queen_tunnel[1].add_insect(fire)
queen_tunnel[2].add_insect(ninja)
queen_tunnel[8].add_insect(front)
side_tunnel[0].add_insect(side)
queen.action(colony)
print('Turn2--------------------------------')
tank = ants.TankAnt()
guard = ants.BodyguardAnt()
queen_tank = ants.TankAnt()
queen_tunnel[6].add_insect(tank)
print("insert tank")
queen_tunnel[1].add_insect(guard)
queen_tunnel[7].add_insect(queen_tank)  
queen.action(colony)
print('Turn3--------------------------')
thrower1 = ants.ThrowerAnt()
thrower2 = ants.ThrowerAnt()
queen_tunnel[6].add_insect(thrower1)

queen_tunnel[5].add_insect(thrower2)
queen.action(colony)
